services:
  mysql:
    image: mysql:8.4
    container_name: foodstore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: farmshop
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+08:00
    volumes:
      - foodstore_mysql_data:/var/lib/mysql

volumes:
  foodstore_mysql_data:
